services:
  open-policy-agent:
    image: openpolicyagent/opa:latest
    container_name: opa
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "/policies"
    expose:
      - "8181"
    volumes:
      - ./opa:/policies