spring.application.name=opaexperiment

# OPA
opa.url=http://localhost:8181

# JWT
secret: EyUkVXaV5ChhAOiyJ3rQ47bspxwFa59MNNTpKEo+w8oOEv6ZJIp1q9GJLgVkS5rd
access-token-expiration: 900000
refresh-token-expiration: 604800000